### ISSUE TITLE
Your macros in new far2l configuration storage format

### ISSUE THREAD

**Issue by unxed** [corporateshark/far2l-macros#6]
Place this in `~/.config/far2l/settings/key_macros.ini`

```
[KeyMacros/Editor/Alt0]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 0

[KeyMacros/Editor/Alt1]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 1

[KeyMacros/Editor/Alt2]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 2

[KeyMacros/Editor/Alt3]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 3

[KeyMacros/Editor/Alt4]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 4

[KeyMacros/Editor/Alt5]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 5

[KeyMacros/Editor/Alt6]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 6

[KeyMacros/Editor/Alt7]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 7

[KeyMacros/Editor/Alt8]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 8

[KeyMacros/Editor/Alt9]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 9

[KeyMacros/Editor/CtrlDown]
DisableOutput=0x1
Sequence=PgDn

[KeyMacros/Editor/CtrlG]
DisableOutput=0x1
Sequence=AltF8

[KeyMacros/Editor/CtrlUp]
DisableOutput=0x1
Sequence=PgUp

[KeyMacros/Menu/CtrlBrowserForward]
DisableOutput=0x1
Sequence=Ins

[KeyMacros/Shell/Alt0]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 0

[KeyMacros/Shell/Alt1]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 1

[KeyMacros/Shell/Alt2]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 2

[KeyMacros/Shell/Alt3]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 3

[KeyMacros/Shell/Alt4]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 4

[KeyMacros/Shell/Alt5]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 5

[KeyMacros/Shell/Alt6]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 6

[KeyMacros/Shell/Alt7]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 7

[KeyMacros/Shell/Alt8]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 8

[KeyMacros/Shell/Alt9]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 9

[KeyMacros/Shell/Alt=]
DisableOutput=0x1
Sequence=Tab Ctrl\ CtrlPgUp - Tab

[KeyMacros/Shell/AltX]
Sequence=F10

[KeyMacros/Shell/Bs]
DisableOutput=0x1
EmptyCommandLine=0x1
Sequence=CtrlPgUp

[KeyMacros/Shell/Esc]
DisableOutput=0x1
EmptyCommandLine=0x1
Sequence=CtrlO

[KeyMacros/Shell/NumDel]
DisableOutput=0x1
Sequence=F8

[KeyMacros/Viewer/Alt0]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 0

[KeyMacros/Viewer/Alt1]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 1

[KeyMacros/Viewer/Alt2]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 2

[KeyMacros/Viewer/Alt3]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 3

[KeyMacros/Viewer/Alt4]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 4

[KeyMacros/Viewer/Alt5]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 5

[KeyMacros/Viewer/Alt6]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 6

[KeyMacros/Viewer/Alt7]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 7

[KeyMacros/Viewer/Alt8]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 8

[KeyMacros/Viewer/Alt9]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F12 9

```

**Comment by corporateshark** [comment]
@unxed Thank you!

What would be the best way to support both formats?

**Comment by unxed** [comment]
> @unxed Thank you!
> 
> What would be the best way to support both formats?

When distributing far2l's color theme I just mimic ~/.config/far2l folder structure, and have both REG files and ini files in it.

**Comment by elfmz** [comment]
I'd suggest something like installer script that will 
1 detect if there is ~/.config/far2l/settings/config.ini file and  if its not - just copy REG files but..
2 ..if there is such file then its a version 2.3 and need to use key_macros.ini file in same dir. In last case ideally that installer should check if there is such file and it doesn't contain your file - then concat that two files in such way that content of _your_ file should be prior to content of existing file - to ensure that any existing scripts on same keys will not be overriden (when ini file gets read - last entry overrides previous ones).
And if existing ini contains your file - then just don't do anything.
To check if existing ini contains your file you can put some comment into your file, like "; corporateshark's scripts pack installed" and check if its there by grep.

**Comment by singalen** [comment]
Cmd-C now works, BTW.
I also think that Apple-style cursor navigation is a good reason to start distinguishing Ctrl and Cmd in fal2l.
IIRC, Wx does have a way to distinguish them.

**Comment by unxed** [comment]
>  IIRC, Wx does have a way to distinguish them.

wx certainly do have keyboard test app to experiment with :)

**Comment by elfmz** [comment]
> I also think that Apple-style cursor navigation is a good reason to start distinguishing Ctrl and Cmd in fal2l.
> IIRC, Wx does have a way to distinguish them.

In fact, there is already distinguishing between Ctrl and Cmd. Under Mac - Cmd (any) is treated as Left Ctrl, while Ctrl (any) as Right Ctrl.

**Comment by corporateshark** [comment]
> > @unxed Thank you!
> > What would be the best way to support both formats?
> 
> When distributing far2l's color theme I just mimic ~/.config/far2l folder structure, and have both REG files and ini files in it.

Not sure I got you, but it seems you know what needs to be done. Could you please make a pull request for this?

**Comment by corporateshark** [comment]
@unxed Can we close it now?

**Comment by izzylaif** [comment]
In certain distributions, you have to use
[KeyMacros/Shell/Del]
instead of
[KeyMacros/Shell/NumDel]
