### ISSUE TITLE
Mapping Escape?

### ISSUE THREAD

**Issue by macruspareto** [corporateshark/far2l-macros#7]
Hello guys!

My favourite macro from the Windows version of Far is "Escape" key to quickly toggle the panels on/off. The standard sequence is Ctrl-O.

Is it possible to map the Esc key in far2l ?
I tried creating subdirs like 
~/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-KeyMacros/Commands/k-CtrlO
but without any luck and there's no documentation or tutorial on that.

Thanks!

**Comment by corporateshark** [comment]
Hi!

I think the best place to ask this question is far2l's repository https://github.com/elfmz/far2l/issues.

Here we collect only macros which are functional and ready to be added to far2l.
